### ISSUE TITLE
cannot work in (Project from view/camera)

### ISSUE THREAD

**Issue by liunliun** [mrven/Blender-Texel-Density-Checker#3]
it will get a incorrect result when wrap uv from view/camera.

**Comment by mrven** [comment]
When you unwrap from view/camera you get many distorted islands on UV. Addon trying calculate average TD value for UV Island. Because proportions of uv islands and geometry faces is very difference (and non-consistence) addon has calculation error.
I can’t fix that, because can’t fix distortion of uv for individual faces without breaking uv island.

It is not a bug. It is a feature of the calculation algorithm
